-
  #主键
  id: 1
  #代号
  code: BTC
  #名称
  name: 比特币
  #是否虚拟货币
  is_virtual: true
  #小数点
  decimals: 8
  #最小交易额
  min_trading_val: 0.01
  #交易手续费率
  trading_service_rate: 0.0005
  #提现手续费
  withdraw_service_charge: 0.002
-
  #主键
  id: 2
  #代号
  code: ETH
  #名称
  name: 以太币
  #是否虚拟货币
  is_virtual: true
  #小数点
  decimals: 18
  #最小交易额
  min_trading_val: 0.01
  #交易手续费率
  trading_service_rate: 0.001
  #提现手续费
  withdraw_service_charge: 0.01